apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llamafactory-lora-sft
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: nfs-client-test
  volumeMode: Filesystem
