apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: llamafactory-lora-sft
  labels:
    trainer.kubeflow.org/framework: llamafactory
spec:
  mlPolicy:
    numNodes: 1
    torch: {}
  template:
    spec:
      volumeClaimPolicies:
      - templates:
        - metadata:
            name: initializer
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 50Gi
      replicatedJobs:
      - name: dataset-initializer
        template:
          metadata:
            labels:
              trainer.kubeflow.org/trainjob-ancestor-step: dataset-initializer
          spec:
            template:
              spec:
                containers:
                - name: dataset-initializer
                  image: ghcr.io/kubeflow/trainer/dataset-initializer
                  env:
                  - name: STORAGE_URI
                    value: hf://tatsu-lab/alpaca
                  volumeMounts:
                  - mountPath: /workspace
                    name: initializer
      - name: model-initializer
        template:
          metadata:
            labels:
              trainer.kubeflow.org/trainjob-ancestor-step: model-initializer
          spec:
            template:
              spec:
                containers:
                - name: model-initializer
                  image: ghcr.io/kubeflow/trainer/model-initializer
                  env:
                  - name: STORAGE_URI
                    value: hf://Qwen/Qwen2.5-1.5B-Instruct
                  volumeMounts:
                  - name: initializer
                    mountPath: /workspace
      - name: node
        dependsOn:
        - name: dataset-initializer
          status: Complete
        - name: model-initializer
          status: Complete
        template:
          metadata:
            labels:
              trainer.kubeflow.org/trainjob-ancestor-step: trainer
          spec:
            template:
              spec:
                containers:
                - name: node
                  image: ghcr.io/kubeflow/trainer/llamafactory-trainer
                  command:
                  - llamafactory-cli
                  - train
                  - /config/training.yaml
                  resources:
                    limits:
                      nvidia.com/gpu: 1
                  volumeMounts:
                  - mountPath: /workspace
                    name: initializer
                  - mountPath: /config
                    name: training-config
                volumes:
                - name: training-config
                  configMap:
                    name: llamafactory-lora-sft-config
